### PR TITLE
ANXKUBE-308: allow provisioning of additional vm disks

### PR DESCRIPTION
**Pull request by marioreggiori**
### Checklist

* [x] added release notes to `Unreleased` section in [CHANGELOG.md](CHANGELOG.md), if user facing change

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

**Comment by LittleFox94** [comment]
@marioreggiori can you raise an internal issue to refactor multi disk handling in our Terraform provider using this?

**Comment by LittleFox94** [comment]
Also, should we add an integration test for this?

**Comment by marioreggiori** [comment]
> Also, should we add an integration test for this?

Thought about that too. But as it can only break if the engine API breaks, I don't think it is really necessary ..also considering that we want to deprecate this client as soon as the generic bindings exists.

**Comment by LittleFox94** [comment]
API looks good to me :+1:

**Review by eiabea — APPROVED** [review]

**Pull request merged**
